trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - checkout: self
    submodules: true

  - script: |
      make zip
    displayName: 'Build and create zip file'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/bin'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Part-B-456.zip'
      replaceExistingArchive: true
    displayName: 'Create Zip Archive'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Part-B-456'
    displayName: 'Publish build artifacts'
  
  - script: |
     echo "Publishing Universal Package"
     ls $(Build.ArtifactStagingDirectory)
    displayName: 'List Build Directory Contents'
  
  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'cfea71f5-a5dc-464b-9aa0-a7ce065ef4b2/7fe50ba5-b047-4770-b7c6-36d8606a4c99'
      vstsFeedPackagePublish: 'part-b-456'
      versionOption: 'patch'