name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      # You can add more steps here to build and test your code
      # For example:
      # - name: Build
      #   run: make
      
      # - name: Test
      #   run: make test

  process_part_b_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if Part-b.yaml exists
        run: '[ -f "Part-b.yaml" ] && echo "File exists" || echo "File not found"'
      
      - name: Display Part-b.yaml contents
        run: cat Part-b.yaml
        if: success()  # Only run this step if the file exists
      
      # You can add more steps here to process the Part-b.yaml file
      # For example, you could validate its syntax, extract information, etc.
