name: Build and Publish Binaries

on:
  push:
    branches:
      - '*'  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ toolchain
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc'  # Specify the C++ compiler you want to use, e.g., 'gcc' or 'clang'
        cmake: 'latest'  # Use the latest version of CMake

    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Create build directory
      run: mkdir build

    - name: Build project
      working-directory: ./build
      run: |
        cmake ..
        make

    - name: Publish binaries
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/path/to/your/executable  # Adjust path to your executables within the build directory
