name: Build and Publish Binaries

on:
  push:
    branches:
      - '*'  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Create build directory
      run: mkdir build

    - name: Build project
      working-directory: ./build
      run: make

    - name: Publish binaries
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/path/to/your/executable  # Adjust path to your .exe files within the build directory
